
title: Dannyb0t Hacks - CyberSecurity
description: >- # this means to ignore newlines until "baseurl:"
  Security Engineer, always learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: danielmyong

theme: minima
  
plugins:
  - jekyll-feed
