
title: Daniel Myong - CyberSecurity Walkthroughs
email: dannyb0t@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Cybersecurity Operations Engineer, always learning
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: danielmyong

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
remote_theme: jekyll/minima
minima:
  skin: dark
exclude:
  - Gemfile.lock
